apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-test
  labels:
    app: next-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: next-test
  template:
    metadata:
      labels:
        app: next-test
    spec:
      containers:
        - name: nextjs
          image: beddows/next-test:0.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: next-test-service
spec:
  selector:
    app: next-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: next-test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: next-test.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: next-test-service
            port:
              number: 80
